-name:Deploy to Tomcat
 host:web
 become:yes
 tasks:
    -name:Copy War to Tomcat
     copy:
       src:"/home/samiksha/Devops6D/AnsibleP/target/AnsibleP.war"
       dest:"/opt/tomcat/webapps/AnsibleP.war"
       
